scratch_bytes: 1148928
run_time {
  nanos: 90112
}
algorithm {
  algo_id: 12
  tuning_knobs {
    key: 5
    value: 1
  }
  tuning_knobs {
    key: 6
    value: 0
  }
  tuning_knobs {
    key: 7
    value: 1
  }
  tuning_knobs {
    key: 10
    value: 1
  }
  is_cudnn_frontend: true
  workspace_size {
    value: 1148928
  }
}
