"""Persist search budgets so interrupted cycles keep their original settings."""
import json
from pathlib import Path

def cycle_search_settings(root, cycle, requested, completed, stage):
    if not 1 <= requested <= 10000:
        raise ValueError('Search simulations must be within 1..10000')
    path=Path(root)/'cycle_settings'/f'cycle-{cycle:06d}.json'
    record=json.loads(path.read_text()) if path.exists() else None
    if record is not None:
        if record.get('cycle')!=cycle or not 1<=record.get('simulations',0)<=10000:
            raise ValueError('Invalid saved cycle settings; preserve and inspect the file')
    if stage=='before':
        # Existing pre-change data was generated by the controller fixed at 200.
        effective=record['simulations'] if completed and record else (200 if completed else requested)
        record=dict(schema_version=1,cycle=cycle,simulations=effective,
            games=8,training_steps=64,learning_rate=0.0001,late_temperature=1,
            selfplay_seed_base=20401004+cycle*1000,
            source='legacy_fixed_200' if completed and not record else 'controller')
        path.parent.mkdir(parents=True,exist_ok=True)
        temporary=path.with_suffix('.tmp')
        temporary.write_text(json.dumps(record,indent=2)+'\n')
        temporary.replace(path)
    else:
        if record is None:
            raise ValueError('Missing cycle settings; run the before check first')
        effective=record['simulations']
        if effective!=requested:
            raise ValueError('Completed cycle search budget differs from the requested after-check')
    return dict(simulations_for_cycle=effective,requested_simulations=requested,
        search_change_deferred=effective!=requested,settings_file=str(path))
